/*
   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to You under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
var showControllersOnly = false;
var seriesFilter = "";
var filtersOnlySampleSeries = true;

/*
 * Add header in statistics table to group metrics by category
 * format
 *
 */
function summaryTableHeader(header) {
    var newRow = header.insertRow(-1);
    newRow.className = "tablesorter-no-sort";
    var cell = document.createElement('th');
    cell.setAttribute("data-sorter", false);
    cell.colSpan = 1;
    cell.innerHTML = "Requests";
    newRow.appendChild(cell);

    cell = document.createElement('th');
    cell.setAttribute("data-sorter", false);
    cell.colSpan = 3;
    cell.innerHTML = "Executions";
    newRow.appendChild(cell);

    cell = document.createElement('th');
    cell.setAttribute("data-sorter", false);
    cell.colSpan = 7;
    cell.innerHTML = "Response Times (ms)";
    newRow.appendChild(cell);

    cell = document.createElement('th');
    cell.setAttribute("data-sorter", false);
    cell.colSpan = 1;
    cell.innerHTML = "Throughput";
    newRow.appendChild(cell);

    cell = document.createElement('th');
    cell.setAttribute("data-sorter", false);
    cell.colSpan = 2;
    cell.innerHTML = "Network (KB/sec)";
    newRow.appendChild(cell);
}

/*
 * Populates the table identified by id parameter with the specified data and
 * format
 *
 */
function createTable(table, info, formatter, defaultSorts, seriesIndex, headerCreator) {
    var tableRef = table[0];

    // Create header and populate it with data.titles array
    var header = tableRef.createTHead();

    // Call callback is available
    if(headerCreator) {
        headerCreator(header);
    }

    var newRow = header.insertRow(-1);
    for (var index = 0; index < info.titles.length; index++) {
        var cell = document.createElement('th');
        cell.innerHTML = info.titles[index];
        newRow.appendChild(cell);
    }

    var tBody;

    // Create overall body if defined
    if(info.overall){
        tBody = document.createElement('tbody');
        tBody.className = "tablesorter-no-sort";
        tableRef.appendChild(tBody);
        var newRow = tBody.insertRow(-1);
        var data = info.overall.data;
        for(var index=0;index < data.length; index++){
            var cell = newRow.insertCell(-1);
            cell.innerHTML = formatter ? formatter(index, data[index]): data[index];
        }
    }

    // Create regular body
    tBody = document.createElement('tbody');
    tableRef.appendChild(tBody);

    var regexp;
    if(seriesFilter) {
        regexp = new RegExp(seriesFilter, 'i');
    }
    // Populate body with data.items array
    for(var index=0; index < info.items.length; index++){
        var item = info.items[index];
        if((!regexp || filtersOnlySampleSeries && !info.supportsControllersDiscrimination || regexp.test(item.data[seriesIndex]))
                &&
                (!showControllersOnly || !info.supportsControllersDiscrimination || item.isController)){
            if(item.data.length > 0) {
                var newRow = tBody.insertRow(-1);
                for(var col=0; col < item.data.length; col++){
                    var cell = newRow.insertCell(-1);
                    cell.innerHTML = formatter ? formatter(col, item.data[col]) : item.data[col];
                }
            }
        }
    }

    // Add support of columns sort
    table.tablesorter({sortList : defaultSorts});
}

$(document).ready(function() {

    // Customize table sorter default options
    $.extend( $.tablesorter.defaults, {
        theme: 'blue',
        cssInfoBlock: "tablesorter-no-sort",
        widthFixed: true,
        widgets: ['zebra']
    });

    var data = {"OkPercent": 52.355147978324304, "KoPercent": 47.644852021675696};
    var dataset = [
        {
            "label" : "FAIL",
            "data" : data.KoPercent,
            "color" : "#FF6347"
        },
        {
            "label" : "PASS",
            "data" : data.OkPercent,
            "color" : "#9ACD32"
        }];
    $.plot($("#flot-requests-summary"), dataset, {
        series : {
            pie : {
                show : true,
                radius : 1,
                label : {
                    show : true,
                    radius : 3 / 4,
                    formatter : function(label, series) {
                        return '<div style="font-size:8pt;text-align:center;padding:2px;color:white;">'
                            + label
                            + '<br/>'
                            + Math.round10(series.percent, -2)
                            + '%</div>';
                    },
                    background : {
                        opacity : 0.5,
                        color : '#000'
                    }
                }
            }
        },
        legend : {
            show : true
        }
    });

    // Creates APDEX table
    createTable($("#apdexTable"), {"supportsControllersDiscrimination": true, "overall": {"data": [0.3997776954427566, 500, 1500, "Total"], "isController": false}, "titles": ["Apdex", "T (Toleration threshold)", "F (Frustration threshold)", "Label"], "items": [{"data": [0.805, 500, 1500, "GetInspectionDetail"], "isController": false}, {"data": [0.435, 500, 1500, "SubmitInspection"], "isController": false}, {"data": [0.0, 500, 1500, "Create Inspection"], "isController": true}, {"data": [0.625, 500, 1500, "StartInspection"], "isController": false}, {"data": [0.882943143812709, 500, 1500, "GetAccessToken"], "isController": false}, {"data": [0.8016666666666666, 500, 1500, "AssignInspector"], "isController": false}, {"data": [0.0016666666666666668, 500, 1500, "SaveInspectionDetails"], "isController": false}, {"data": [0.025, 500, 1500, "SaveInspectionVehicle"], "isController": false}, {"data": [0.023333333333333334, 500, 1500, "SaveInspectionMeasurements"], "isController": false}]}, function(index, item){
        switch(index){
            case 0:
                item = item.toFixed(3);
                break;
            case 1:
            case 2:
                item = formatDuration(item);
                break;
        }
        return item;
    }, [[0, 0]], 3);

    // Create statistics table
    createTable($("#statisticsTable"), {"supportsControllersDiscrimination": true, "overall": {"data": ["Total", 2399, 1143, 47.644852021675696, 18691.370154230983, 0, 207075, 161.0, 113604.0, 155373.0, 179582.0, 3.2947186991423294, 6.4587954156852785, 6.311242452893351], "isController": false}, "titles": ["Label", "#Samples", "FAIL", "Error %", "Average", "Min", "Max", "Median", "90th pct", "95th pct", "99th pct", "Transactions/s", "Received", "Sent"], "items": [{"data": ["GetInspectionDetail", 300, 53, 17.666666666666668, 177.72666666666672, 0, 13560, 127.0, 275.4000000000002, 379.5999999999997, 676.98, 0.949688660400832, 1.4870881665231583, 0.6521009982019229], "isController": false}, {"data": ["SubmitInspection", 300, 132, 44.0, 2395.6366666666677, 53, 12372, 556.0, 6802.900000000003, 8821.299999999997, 11395.050000000001, 0.8701301714736525, 1.6786487821078033, 1.1673226783476809], "isController": false}, {"data": ["Create Inspection", 300, 292, 97.33333333333333, 149484.93666666673, 5444, 214825, 154034.0, 186499.0, 189523.8, 206528.20000000004, 1.3945121299313437, 21.927423124613604, 21.3638668179906], "isController": true}, {"data": ["StartInspection", 300, 53, 17.666666666666668, 33858.35333333334, 101, 207075, 198.0, 159969.7, 176785.59999999998, 189604.45, 1.0313637723161335, 0.8779249100564843, 0.998529339720913], "isController": false}, {"data": ["GetAccessToken", 299, 29, 9.698996655518394, 415.4916387959867, 104, 6980, 118.0, 559.0, 2770.0, 5735.0, 4.2728325021078355, 9.331944558569244, 2.353396026551581], "isController": false}, {"data": ["AssignInspector", 300, 53, 17.666666666666668, 175.16666666666666, 0, 1013, 156.0, 371.80000000000007, 429.1499999999998, 725.8800000000001, 0.8704432296925595, 0.9031868558720101, 0.6186833929586946], "isController": false}, {"data": ["SaveInspectionDetails", 300, 289, 96.33333333333333, 18004.403333333354, 65, 181384, 137.5, 90238.60000000021, 131572.29999999996, 169000.94000000006, 0.8181297553792031, 1.2539063565273119, 2.071426243045897], "isController": false}, {"data": ["SaveInspectionVehicle", 300, 263, 87.66666666666667, 93631.68666666668, 89, 204768, 117272.0, 169443.3, 176457.19999999998, 195811.56, 0.9427025396406418, 3.644791205135215, 1.2784912202970142], "isController": false}, {"data": ["SaveInspectionMeasurements", 300, 271, 90.33333333333333, 811.5766666666659, 62, 32378, 144.0, 1027.9000000000003, 3082.8499999999885, 18374.770000000037, 0.9460588763974078, 2.570095818025575, 6.7869746416802], "isController": false}]}, function(index, item){
        switch(index){
            // Errors pct
            case 3:
                item = item.toFixed(2) + '%';
                break;
            // Mean
            case 4:
            // Mean
            case 7:
            // Median
            case 8:
            // Percentile 1
            case 9:
            // Percentile 2
            case 10:
            // Percentile 3
            case 11:
            // Throughput
            case 12:
            // Kbytes/s
            case 13:
            // Sent Kbytes/s
                item = item.toFixed(2);
                break;
        }
        return item;
    }, [[0, 0]], 0, summaryTableHeader);

    // Create error table
    createTable($("#errorsTable"), {"supportsControllersDiscrimination": false, "titles": ["Type of error", "Number of errors", "% in errors", "% in all samples"], "items": [{"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One%20or%20more%20errors%20occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Threading.Tasks.Task.ThrowIfExceptional(Boolean%20includeTaskCanceledExceptions)\\\\r\\\\n%20%20%20at%20System.Threading.Tasks.Task`1.GetResultCore(Boolean%20waitCompletionNotification)\\\\r\\\\n%20%20%20at%20CVSE.Model.CVNSCEntities.GetNextSequenceValue(String%20pkColumnName)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\PTSEntities.Context.cs:line%2040\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Inspection.VipVehicleInspectionRepository.AddNew(CvVipVehicleInspection%20entity,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Inspection\\\\\\\\VipVehicleInspectionRepository.cs:line%2034\\\\r\\\\n%20%20%20at%20VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo%20inspectionInfo,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line%20233\\\\r\\\\n%20%20%20at%20VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo%20inspectionInfo)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line%2036&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The%20underlying%20provider%20failed%20on%20Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout%20expired.%20%20The%20timeout%20period%20elapsed%20prior%20to%20obtaining%20a%20connection%20from%20the%20pool.%20%20This%20may%20have%20occurred%20because%20all%20pooled%20connections%20were%20in%20use%20and%20max%20pool%20size%20was%20reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Common.ADP.ExceptionWithStackTrace(Exception%20e)\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}&amp;inspectorId=35185", 10, 0.8748906386701663, 0.4168403501458941], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One%20or%20more%20errors%20occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Threading.Tasks.Task.ThrowIfExceptional(Boolean%20includeTaskCanceledExceptions)\\\\r\\\\n%20%20%20at%20System.Threading.Tasks.Task`1.GetResultCore(Boolean%20waitCompletionNotification)\\\\r\\\\n%20%20%20at%20CVSE.Model.CVNSCEntities.GetNextSequenceValue(String%20pkColumnName)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\PTSEntities.Context.cs:line%2040\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Interaction.InteractionRepository.CreateNewInteraction(CvNscInteraction%20interaction,%20String%20interactionTypeCode,%20String%20interactionStatusCode,%20Nullable`1%20assignedToPersonId,%20Nullable`1%20loggedInPersonId,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line%20121\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Interaction.InteractionRepository.CreateVipInspectionInteraction(Int64%20vipVehicleInspectionId,%20Boolean%20isCvip,%20Nullable`1%20loggedInPersonId,%20Dictionary`2%20headers,%20String%20interactionStatusCode,%20Nullable`1%20assignedToPersonId)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line%20115\\\\r\\\\n%20%20%20at%20VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo%20inspectionInfo,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line%20237\\\\r\\\\n%20%20%20at%20VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo%20inspectionInfo)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line%2036&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The%20underlying%20provider%20failed%20on%20Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout%20expired.%20%20The%20timeout%20period%20elapsed%20prior%20to%20obtaining%20a%20connection%20from%20the%20pool.%20%20This%20may%20have%20occurred%20because%20all%20pooled%20connections%20were%20in%20use%20and%20max%20pool%20size%20was%20reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Common.ADP.ExceptionWithStackTrace(Exception%20e)\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}&amp;inspectorId=35185", 1, 0.08748906386701662, 0.041684035014589414], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;An%20error%20occurred%20while%20updating%20the%20entries.%20See%20the%20inner%20exception%20for%20details.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Infrastructure.DbUpdateException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Entity.Internal.InternalContext.SaveChanges()\\\\r\\\\n%20%20%20at%20VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo%20inspectionInfo,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line%20386\\\\r\\\\n%20%20%20at%20VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo%20inspectionInfo)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line%2036&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;An%20error%20occurred%20while%20updating%20the%20entries.%20See%20the%20inner%20exception%20for%20details.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.UpdateException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1%20func,%20IDbExecutionStrategy%20executionStrategy,%20Boolean%20startLocalTransaction,%20Boolean%20releaseConnectionOnSuccess)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions%20options,%20IDbExecutionStrategy%20executionStrategy,%20Boolean%20startLocalTransaction)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1%20operation)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions%20options,%20Boolean%20executeInExistingTransaction)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Internal.InternalContext.SaveChanges()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Execution%20Timeout%20Expired.%20%20The%20timeout%20period%20elapsed%20prior%20to%20completion%20of%20the%20operation%20or%20the%20server%20is%20not%20responding.&quot;,&quot;exceptionType&quot;:&quot;System.Data.SqlClient.SqlException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.SqlClient.SqlConnection.OnError(SqlException%20exception,%20Boolean%20breakConnection,%20Action`1%20wrapCloseInAction)\\\\r\\\\n%20%20%20at%20System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject%20stateObj,%20Boolean%20callerHasConnectionLock,%20Boolean%20asyncClose)\\\\r\\\\n%20%20%20at%20System.Data.SqlClient.TdsParser.TryRun(RunBehavior%20runBehavior,%20SqlCommand%20cmdHandler,%20SqlDataReader%20dataStream,%20BulkCopySimpleResultSet%20bulkCopyHandler,%20TdsParserStateObject%20stateObj,%20Boolean&amp;%20dataReady)\\\\r\\\\n%20%20%20at%20System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()\\\\r\\\\n%20%20%20at%20System.Data.SqlClient.SqlDataReader.get_MetaData()\\\\r\\\\n%20%20%20at%20System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader%20ds,%20RunBehavior%20runBehavior,%20String%20resetOptionsString,%20Boolean%20isInternal,%20Boolean%20forDescribeParameterEncryption,%20Boolean%20shouldCacheForAlwaysEncrypted)\\\\r\\\\n%20%20%20at%20System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior%20cmdBehavior,%20RunBehavior%20runBehavior,%20Boolean%20returnStream,%20Boolean%20async,%20Int32%20timeout,%20Task&amp;%20task,%20Boolean%20asyncWrite,%20Boolean%20inRetry,%20SqlDataReader%20ds,%20Boolean%20describeParameterEncryptionRequest)\\\\r\\\\n%20%20%20at%20System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior%20cmdBehavior,%20RunBehavior%20runBehavior,%20Boolean%20returnStream,%20String%20method,%20TaskCompletionSource`1%20completion,%20Int32%20timeout,%20Task&amp;%20task,%20Boolean&amp;%20usedCache,%20Boolean%20asyncWrite,%20Boolean%20inRetry)\\\\r\\\\n%20%20%20at%20System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior%20cmdBehavior,%20RunBehavior%20runBehavior,%20Boolean%20returnStream,%20String%20method)\\\\r\\\\n%20%20%20at%20System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior%20behavior,%20String%20method)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget%20target,%20Func`3%20operation,%20TInterceptionContext%20interceptionContext,%20Action`3%20executing,%20Action`3%20executed)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand%20command,%20DbCommandInterceptionContext%20interceptionContext)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2%20identifierValues,%20List`1%20generatedValues)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The%20wait%20operation%20timed%20out&quot;,&quot;exceptionType&quot;:&quot;System.ComponentModel.Win32Exception&quot;,&quot;stackTrace&quot;:null}}}}&amp;inspectorId=35185", 1, 0.08748906386701662, 0.041684035014589414], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 91: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/vehicleDetails?inspectionId={&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One or more errors occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\\\\r\\\\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\\\\r\\\\n   at CVSE.Model.CVNSCEntities.GetNextCustomSequenceValue(String sequenceName) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\CustomEntityMethods.cs:line 9\\\\r\\\\n   at VIP.Data.Repositories.Inspection.InspectionRepository.AddNew(CvVipInspection entity, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Inspection\\\\\\\\InspectionRepository.cs:line 41\\\\r\\\\n   at VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo inspectionInfo, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line 209\\\\r\\\\n   at VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo inspectionInfo) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line 36&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The underlying provider failed on Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}", 2, 0.17497812773403323, 0.08336807002917883], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;Authorization%20has%20been%20denied%20for%20this%20request.&quot;}&amp;inspectorId=35185", 30, 2.6246719160104988, 1.2505210504376825], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 91: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/vehicleDetails?inspectionId={&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One or more errors occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\\\\r\\\\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\\\\r\\\\n   at CVSE.Model.CVNSCEntities.GetNextSequenceValue(String pkColumnName) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\PTSEntities.Context.cs:line 40\\\\r\\\\n   at VIP.Data.Repositories.Inspection.VipVehicleInspectionRepository.AddNew(CvVipVehicleInspection entity, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Inspection\\\\\\\\VipVehicleInspectionRepository.cs:line 34\\\\r\\\\n   at VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo inspectionInfo, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line 233\\\\r\\\\n   at VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo inspectionInfo) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line 36&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The underlying provider failed on Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}", 10, 0.8748906386701663, 0.4168403501458941], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 91: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/vehicleDetails?inspectionId={&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One or more errors occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\\\\r\\\\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\\\\r\\\\n   at CVSE.Model.CVNSCEntities.GetNextSequenceValue(String pkColumnName) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\PTSEntities.Context.cs:line 40\\\\r\\\\n   at VIP.Data.Repositories.Interaction.InteractionRepository.CreateNewInteraction(CvNscInteraction interaction, String interactionTypeCode, String interactionStatusCode, Nullable`1 assignedToPersonId, Nullable`1 loggedInPersonId, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line 121\\\\r\\\\n   at VIP.Data.Repositories.Interaction.InteractionRepository.CreateVipInspectionInteraction(Int64 vipVehicleInspectionId, Boolean isCvip, Nullable`1 loggedInPersonId, Dictionary`2 headers, String interactionStatusCode, Nullable`1 assignedToPersonId) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line 115\\\\r\\\\n   at VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo inspectionInfo, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line 237\\\\r\\\\n   at VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo inspectionInfo) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line 36&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The underlying provider failed on Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}", 1, 0.08748906386701662, 0.041684035014589414], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 91: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/vehicleDetails?inspectionId={&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One or more errors occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\\\\r\\\\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\\\\r\\\\n   at CVSE.Model.CVNSCEntities.GetNextCustomSequenceValue(String sequenceName) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\CustomEntityMethods.cs:line 9\\\\r\\\\n   at VIP.Data.Repositories.Interaction.InteractionRepository.GetInteractionNumber(CVSE_INTERACTION_TYPE interactionType) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line 151\\\\r\\\\n   at VIP.Data.Repositories.Interaction.InteractionRepository.CreateNewInteraction(CvNscInteraction interaction, String interactionTypeCode, String interactionStatusCode, Nullable`1 assignedToPersonId, Nullable`1 loggedInPersonId, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line 121\\\\r\\\\n   at VIP.Data.Repositories.Interaction.InteractionRepository.CreateVipInspectionInteraction(Int64 vipVehicleInspectionId, Boolean isCvip, Nullable`1 loggedInPersonId, Dictionary`2 headers, String interactionStatusCode, Nullable`1 assignedToPersonId) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line 115\\\\r\\\\n   at VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo inspectionInfo, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line 237\\\\r\\\\n   at VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo inspectionInfo) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line 36&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The underlying provider failed on Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}", 5, 0.4374453193350831, 0.20842017507294705], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 91: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/vehicleDetails?inspectionId={&quot;message&quot;:&quot;Authorization has been denied for this request.&quot;}", 30, 2.6246719160104988, 1.2505210504376825], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One%20or%20more%20errors%20occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Threading.Tasks.Task.ThrowIfExceptional(Boolean%20includeTaskCanceledExceptions)\\\\r\\\\n%20%20%20at%20System.Threading.Tasks.Task`1.GetResultCore(Boolean%20waitCompletionNotification)\\\\r\\\\n%20%20%20at%20CVSE.Model.CVNSCEntities.GetNextSequenceValue(String%20pkColumnName)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\PTSEntities.Context.cs:line%2040\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Interaction.InteractionHistoryRepository.AddNew(CvNscInteractionHistory%20entity,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionHistoryRepository.cs:line%2022\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Interaction.InteractionRepository.CreateNewInteraction(CvNscInteraction%20interaction,%20String%20interactionTypeCode,%20String%20interactionStatusCode,%20Nullable`1%20assignedToPersonId,%20Nullable`1%20loggedInPersonId,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line%20145\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Interaction.InteractionRepository.CreateVipInspectionInteraction(Int64%20vipVehicleInspectionId,%20Boolean%20isCvip,%20Nullable`1%20loggedInPersonId,%20Dictionary`2%20headers,%20String%20interactionStatusCode,%20Nullable`1%20assignedToPersonId)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line%20115\\\\r\\\\n%20%20%20at%20VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo%20inspectionInfo,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line%20237\\\\r\\\\n%20%20%20at%20VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo%20inspectionInfo)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line%2036&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The%20underlying%20provider%20failed%20on%20Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout%20expired.%20%20The%20timeout%20period%20elapsed%20prior%20to%20obtaining%20a%20connection%20from%20the%20pool.%20%20This%20may%20have%20occurred%20because%20all%20pooled%20connections%20were%20in%20use%20and%20max%20pool%20size%20was%20reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Common.ADP.ExceptionWithStackTrace(Exception%20e)\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}&amp;inspectorId=35185", 3, 0.26246719160104987, 0.12505210504376824], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 91: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/vehicleDetails?inspectionId={&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;An error occurred while updating the entries. See the inner exception for details.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Infrastructure.DbUpdateException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Entity.Internal.InternalContext.SaveChanges()\\\\r\\\\n   at VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo inspectionInfo, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line 386\\\\r\\\\n   at VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo inspectionInfo) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line 36&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;An error occurred while updating the entries. See the inner exception for details.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.UpdateException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)\\\\r\\\\n   at System.Data.Entity.Internal.InternalContext.SaveChanges()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.&quot;,&quot;exceptionType&quot;:&quot;System.Data.SqlClient.SqlException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\\\\r\\\\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\\\\r\\\\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&amp; dataReady)\\\\r\\\\n   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()\\\\r\\\\n   at System.Data.SqlClient.SqlDataReader.get_MetaData()\\\\r\\\\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\\\\r\\\\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task&amp; task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\\\\r\\\\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task&amp; task, Boolean&amp; usedCache, Boolean asyncWrite, Boolean inRetry)\\\\r\\\\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)\\\\r\\\\n   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)\\\\r\\\\n   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)\\\\r\\\\n   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)\\\\r\\\\n   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)\\\\r\\\\n   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The wait operation timed out&quot;,&quot;exceptionType&quot;:&quot;System.ComponentModel.Win32Exception&quot;,&quot;stackTrace&quot;:null}}}}", 1, 0.08748906386701662, 0.041684035014589414], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 91: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/vehicleDetails?inspectionId={&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One or more errors occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\\\\r\\\\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\\\\r\\\\n   at CVSE.Model.CVNSCEntities.GetNextSequenceValue(String pkColumnName) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\PTSEntities.Context.cs:line 40\\\\r\\\\n   at VIP.Data.Repositories.Interaction.InteractionHistoryRepository.AddNew(CvNscInteractionHistory entity, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionHistoryRepository.cs:line 22\\\\r\\\\n   at VIP.Data.Repositories.Interaction.InteractionRepository.CreateNewInteraction(CvNscInteraction interaction, String interactionTypeCode, String interactionStatusCode, Nullable`1 assignedToPersonId, Nullable`1 loggedInPersonId, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line 145\\\\r\\\\n   at VIP.Data.Repositories.Interaction.InteractionRepository.CreateVipInspectionInteraction(Int64 vipVehicleInspectionId, Boolean isCvip, Nullable`1 loggedInPersonId, Dictionary`2 headers, String interactionStatusCode, Nullable`1 assignedToPersonId) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line 115\\\\r\\\\n   at VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo inspectionInfo, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line 237\\\\r\\\\n   at VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo inspectionInfo) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line 36&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The underlying provider failed on Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}", 3, 0.26246719160104987, 0.12505210504376824], "isController": false}, {"data": ["500/Internal Server Error", 887, 77.60279965004375, 36.97373905794081], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 91: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/vehicleDetails?inspectionId={&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One or more errors occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\\\\r\\\\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\\\\r\\\\n   at CVSE.Model.CVNSCEntities.GetNextSequenceValue(String pkColumnName) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\PTSEntities.Context.cs:line 40\\\\r\\\\n   at VIP.Data.Repositories.Inspection.InspectionRepository.AddNew(CvVipInspection entity, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Inspection\\\\\\\\InspectionRepository.cs:line 40\\\\r\\\\n   at VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo inspectionInfo, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line 209\\\\r\\\\n   at VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo inspectionInfo) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line 36&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The underlying provider failed on Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}", 1, 0.08748906386701662, 0.041684035014589414], "isController": false}, {"data": ["401/Unauthorized", 150, 13.123359580052494, 6.2526052521884115], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One%20or%20more%20errors%20occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Threading.Tasks.Task.ThrowIfExceptional(Boolean%20includeTaskCanceledExceptions)\\\\r\\\\n%20%20%20at%20System.Threading.Tasks.Task`1.GetResultCore(Boolean%20waitCompletionNotification)\\\\r\\\\n%20%20%20at%20CVSE.Model.CVNSCEntities.GetNextCustomSequenceValue(String%20sequenceName)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\CustomEntityMethods.cs:line%209\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Inspection.InspectionRepository.AddNew(CvVipInspection%20entity,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Inspection\\\\\\\\InspectionRepository.cs:line%2041\\\\r\\\\n%20%20%20at%20VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo%20inspectionInfo,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line%20209\\\\r\\\\n%20%20%20at%20VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo%20inspectionInfo)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line%2036&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The%20underlying%20provider%20failed%20on%20Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout%20expired.%20%20The%20timeout%20period%20elapsed%20prior%20to%20obtaining%20a%20connection%20from%20the%20pool.%20%20This%20may%20have%20occurred%20because%20all%20pooled%20connections%20were%20in%20use%20and%20max%20pool%20size%20was%20reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Common.ADP.ExceptionWithStackTrace(Exception%20e)\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}&amp;inspectorId=35185", 2, 0.17497812773403323, 0.08336807002917883], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One%20or%20more%20errors%20occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Threading.Tasks.Task.ThrowIfExceptional(Boolean%20includeTaskCanceledExceptions)\\\\r\\\\n%20%20%20at%20System.Threading.Tasks.Task`1.GetResultCore(Boolean%20waitCompletionNotification)\\\\r\\\\n%20%20%20at%20CVSE.Model.CVNSCEntities.GetNextSequenceValue(String%20pkColumnName)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\PTSEntities.Context.cs:line%2040\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Inspection.InspectionRepository.AddNew(CvVipInspection%20entity,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Inspection\\\\\\\\InspectionRepository.cs:line%2040\\\\r\\\\n%20%20%20at%20VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo%20inspectionInfo,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line%20209\\\\r\\\\n%20%20%20at%20VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo%20inspectionInfo)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line%2036&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The%20underlying%20provider%20failed%20on%20Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout%20expired.%20%20The%20timeout%20period%20elapsed%20prior%20to%20obtaining%20a%20connection%20from%20the%20pool.%20%20This%20may%20have%20occurred%20because%20all%20pooled%20connections%20were%20in%20use%20and%20max%20pool%20size%20was%20reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Common.ADP.ExceptionWithStackTrace(Exception%20e)\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}&amp;inspectorId=35185", 1, 0.08748906386701662, 0.041684035014589414], "isController": false}, {"data": ["Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One%20or%20more%20errors%20occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Threading.Tasks.Task.ThrowIfExceptional(Boolean%20includeTaskCanceledExceptions)\\\\r\\\\n%20%20%20at%20System.Threading.Tasks.Task`1.GetResultCore(Boolean%20waitCompletionNotification)\\\\r\\\\n%20%20%20at%20CVSE.Model.CVNSCEntities.GetNextCustomSequenceValue(String%20sequenceName)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\CustomEntityMethods.cs:line%209\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Interaction.InteractionRepository.GetInteractionNumber(CVSE_INTERACTION_TYPE%20interactionType)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line%20151\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Interaction.InteractionRepository.CreateNewInteraction(CvNscInteraction%20interaction,%20String%20interactionTypeCode,%20String%20interactionStatusCode,%20Nullable`1%20assignedToPersonId,%20Nullable`1%20loggedInPersonId,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line%20121\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Interaction.InteractionRepository.CreateVipInspectionInteraction(Int64%20vipVehicleInspectionId,%20Boolean%20isCvip,%20Nullable`1%20loggedInPersonId,%20Dictionary`2%20headers,%20String%20interactionStatusCode,%20Nullable`1%20assignedToPersonId)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line%20115\\\\r\\\\n%20%20%20at%20VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo%20inspectionInfo,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line%20237\\\\r\\\\n%20%20%20at%20VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo%20inspectionInfo)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line%2036&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The%20underlying%20provider%20failed%20on%20Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout%20expired.%20%20The%20timeout%20period%20elapsed%20prior%20to%20obtaining%20a%20connection%20from%20the%20pool.%20%20This%20may%20have%20occurred%20because%20all%20pooled%20connections%20were%20in%20use%20and%20max%20pool%20size%20was%20reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Common.ADP.ExceptionWithStackTrace(Exception%20e)\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}&amp;inspectorId=35185", 5, 0.4374453193350831, 0.20842017507294705], "isController": false}]}, function(index, item){
        switch(index){
            case 2:
            case 3:
                item = item.toFixed(2) + '%';
                break;
        }
        return item;
    }, [[1, 1]]);

        // Create top5 errors by sampler
    createTable($("#top5ErrorsBySamplerTable"), {"supportsControllersDiscrimination": false, "overall": {"data": ["Total", 2399, 1143, "500/Internal Server Error", 887, "401/Unauthorized", 150, "Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;Authorization%20has%20been%20denied%20for%20this%20request.&quot;}&amp;inspectorId=35185", 30, "Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 91: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/vehicleDetails?inspectionId={&quot;message&quot;:&quot;Authorization has been denied for this request.&quot;}", 30, "Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One%20or%20more%20errors%20occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Threading.Tasks.Task.ThrowIfExceptional(Boolean%20includeTaskCanceledExceptions)\\\\r\\\\n%20%20%20at%20System.Threading.Tasks.Task`1.GetResultCore(Boolean%20waitCompletionNotification)\\\\r\\\\n%20%20%20at%20CVSE.Model.CVNSCEntities.GetNextSequenceValue(String%20pkColumnName)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\PTSEntities.Context.cs:line%2040\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Inspection.VipVehicleInspectionRepository.AddNew(CvVipVehicleInspection%20entity,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Inspection\\\\\\\\VipVehicleInspectionRepository.cs:line%2034\\\\r\\\\n%20%20%20at%20VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo%20inspectionInfo,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line%20233\\\\r\\\\n%20%20%20at%20VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo%20inspectionInfo)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line%2036&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The%20underlying%20provider%20failed%20on%20Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout%20expired.%20%20The%20timeout%20period%20elapsed%20prior%20to%20obtaining%20a%20connection%20from%20the%20pool.%20%20This%20may%20have%20occurred%20because%20all%20pooled%20connections%20were%20in%20use%20and%20max%20pool%20size%20was%20reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Common.ADP.ExceptionWithStackTrace(Exception%20e)\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}&amp;inspectorId=35185", 10], "isController": false}, "titles": ["Sample", "#Samples", "#Errors", "Error", "#Errors", "Error", "#Errors", "Error", "#Errors", "Error", "#Errors", "Error", "#Errors"], "items": [{"data": ["GetInspectionDetail", 300, 53, "Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 91: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/vehicleDetails?inspectionId={&quot;message&quot;:&quot;Authorization has been denied for this request.&quot;}", 30, "Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 91: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/vehicleDetails?inspectionId={&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One or more errors occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\\\\r\\\\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\\\\r\\\\n   at CVSE.Model.CVNSCEntities.GetNextSequenceValue(String pkColumnName) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\PTSEntities.Context.cs:line 40\\\\r\\\\n   at VIP.Data.Repositories.Inspection.VipVehicleInspectionRepository.AddNew(CvVipVehicleInspection entity, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Inspection\\\\\\\\VipVehicleInspectionRepository.cs:line 34\\\\r\\\\n   at VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo inspectionInfo, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line 233\\\\r\\\\n   at VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo inspectionInfo) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line 36&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The underlying provider failed on Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}", 10, "Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 91: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/vehicleDetails?inspectionId={&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One or more errors occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\\\\r\\\\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\\\\r\\\\n   at CVSE.Model.CVNSCEntities.GetNextCustomSequenceValue(String sequenceName) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\CustomEntityMethods.cs:line 9\\\\r\\\\n   at VIP.Data.Repositories.Interaction.InteractionRepository.GetInteractionNumber(CVSE_INTERACTION_TYPE interactionType) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line 151\\\\r\\\\n   at VIP.Data.Repositories.Interaction.InteractionRepository.CreateNewInteraction(CvNscInteraction interaction, String interactionTypeCode, String interactionStatusCode, Nullable`1 assignedToPersonId, Nullable`1 loggedInPersonId, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line 121\\\\r\\\\n   at VIP.Data.Repositories.Interaction.InteractionRepository.CreateVipInspectionInteraction(Int64 vipVehicleInspectionId, Boolean isCvip, Nullable`1 loggedInPersonId, Dictionary`2 headers, String interactionStatusCode, Nullable`1 assignedToPersonId) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line 115\\\\r\\\\n   at VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo inspectionInfo, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line 237\\\\r\\\\n   at VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo inspectionInfo) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line 36&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The underlying provider failed on Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}", 5, "Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 91: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/vehicleDetails?inspectionId={&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One or more errors occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\\\\r\\\\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\\\\r\\\\n   at CVSE.Model.CVNSCEntities.GetNextSequenceValue(String pkColumnName) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\PTSEntities.Context.cs:line 40\\\\r\\\\n   at VIP.Data.Repositories.Interaction.InteractionHistoryRepository.AddNew(CvNscInteractionHistory entity, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionHistoryRepository.cs:line 22\\\\r\\\\n   at VIP.Data.Repositories.Interaction.InteractionRepository.CreateNewInteraction(CvNscInteraction interaction, String interactionTypeCode, String interactionStatusCode, Nullable`1 assignedToPersonId, Nullable`1 loggedInPersonId, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line 145\\\\r\\\\n   at VIP.Data.Repositories.Interaction.InteractionRepository.CreateVipInspectionInteraction(Int64 vipVehicleInspectionId, Boolean isCvip, Nullable`1 loggedInPersonId, Dictionary`2 headers, String interactionStatusCode, Nullable`1 assignedToPersonId) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line 115\\\\r\\\\n   at VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo inspectionInfo, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line 237\\\\r\\\\n   at VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo inspectionInfo) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line 36&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The underlying provider failed on Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}", 3, "Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 91: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/vehicleDetails?inspectionId={&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One or more errors occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\\\\r\\\\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\\\\r\\\\n   at CVSE.Model.CVNSCEntities.GetNextCustomSequenceValue(String sequenceName) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\CustomEntityMethods.cs:line 9\\\\r\\\\n   at VIP.Data.Repositories.Inspection.InspectionRepository.AddNew(CvVipInspection entity, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Inspection\\\\\\\\InspectionRepository.cs:line 41\\\\r\\\\n   at VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo inspectionInfo, Dictionary`2 headers) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line 209\\\\r\\\\n   at VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo inspectionInfo) in E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line 36&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The underlying provider failed on Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An error has occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n--- End of stack trace from previous location where exception was thrown ---\\\\r\\\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\\r\\\\n   at System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}", 2], "isController": false}, {"data": ["SubmitInspection", 300, 132, "500/Internal Server Error", 102, "401/Unauthorized", 30, null, null, null, null, null, null], "isController": false}, {"data": [], "isController": false}, {"data": ["StartInspection", 300, 53, "401/Unauthorized", 30, "500/Internal Server Error", 23, null, null, null, null, null, null], "isController": false}, {"data": ["GetAccessToken", 299, 29, "500/Internal Server Error", 29, null, null, null, null, null, null, null, null], "isController": false}, {"data": ["AssignInspector", 300, 53, "Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;Authorization%20has%20been%20denied%20for%20this%20request.&quot;}&amp;inspectorId=35185", 30, "Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One%20or%20more%20errors%20occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Threading.Tasks.Task.ThrowIfExceptional(Boolean%20includeTaskCanceledExceptions)\\\\r\\\\n%20%20%20at%20System.Threading.Tasks.Task`1.GetResultCore(Boolean%20waitCompletionNotification)\\\\r\\\\n%20%20%20at%20CVSE.Model.CVNSCEntities.GetNextSequenceValue(String%20pkColumnName)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\PTSEntities.Context.cs:line%2040\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Inspection.VipVehicleInspectionRepository.AddNew(CvVipVehicleInspection%20entity,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Inspection\\\\\\\\VipVehicleInspectionRepository.cs:line%2034\\\\r\\\\n%20%20%20at%20VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo%20inspectionInfo,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line%20233\\\\r\\\\n%20%20%20at%20VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo%20inspectionInfo)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line%2036&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The%20underlying%20provider%20failed%20on%20Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout%20expired.%20%20The%20timeout%20period%20elapsed%20prior%20to%20obtaining%20a%20connection%20from%20the%20pool.%20%20This%20may%20have%20occurred%20because%20all%20pooled%20connections%20were%20in%20use%20and%20max%20pool%20size%20was%20reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Common.ADP.ExceptionWithStackTrace(Exception%20e)\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}&amp;inspectorId=35185", 10, "Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One%20or%20more%20errors%20occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Threading.Tasks.Task.ThrowIfExceptional(Boolean%20includeTaskCanceledExceptions)\\\\r\\\\n%20%20%20at%20System.Threading.Tasks.Task`1.GetResultCore(Boolean%20waitCompletionNotification)\\\\r\\\\n%20%20%20at%20CVSE.Model.CVNSCEntities.GetNextCustomSequenceValue(String%20sequenceName)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\CustomEntityMethods.cs:line%209\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Interaction.InteractionRepository.GetInteractionNumber(CVSE_INTERACTION_TYPE%20interactionType)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line%20151\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Interaction.InteractionRepository.CreateNewInteraction(CvNscInteraction%20interaction,%20String%20interactionTypeCode,%20String%20interactionStatusCode,%20Nullable`1%20assignedToPersonId,%20Nullable`1%20loggedInPersonId,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line%20121\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Interaction.InteractionRepository.CreateVipInspectionInteraction(Int64%20vipVehicleInspectionId,%20Boolean%20isCvip,%20Nullable`1%20loggedInPersonId,%20Dictionary`2%20headers,%20String%20interactionStatusCode,%20Nullable`1%20assignedToPersonId)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line%20115\\\\r\\\\n%20%20%20at%20VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo%20inspectionInfo,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line%20237\\\\r\\\\n%20%20%20at%20VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo%20inspectionInfo)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line%2036&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The%20underlying%20provider%20failed%20on%20Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout%20expired.%20%20The%20timeout%20period%20elapsed%20prior%20to%20obtaining%20a%20connection%20from%20the%20pool.%20%20This%20may%20have%20occurred%20because%20all%20pooled%20connections%20were%20in%20use%20and%20max%20pool%20size%20was%20reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Common.ADP.ExceptionWithStackTrace(Exception%20e)\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}&amp;inspectorId=35185", 5, "Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One%20or%20more%20errors%20occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Threading.Tasks.Task.ThrowIfExceptional(Boolean%20includeTaskCanceledExceptions)\\\\r\\\\n%20%20%20at%20System.Threading.Tasks.Task`1.GetResultCore(Boolean%20waitCompletionNotification)\\\\r\\\\n%20%20%20at%20CVSE.Model.CVNSCEntities.GetNextSequenceValue(String%20pkColumnName)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\PTSEntities.Context.cs:line%2040\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Interaction.InteractionHistoryRepository.AddNew(CvNscInteractionHistory%20entity,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionHistoryRepository.cs:line%2022\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Interaction.InteractionRepository.CreateNewInteraction(CvNscInteraction%20interaction,%20String%20interactionTypeCode,%20String%20interactionStatusCode,%20Nullable`1%20assignedToPersonId,%20Nullable`1%20loggedInPersonId,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line%20145\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Interaction.InteractionRepository.CreateVipInspectionInteraction(Int64%20vipVehicleInspectionId,%20Boolean%20isCvip,%20Nullable`1%20loggedInPersonId,%20Dictionary`2%20headers,%20String%20interactionStatusCode,%20Nullable`1%20assignedToPersonId)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Interaction\\\\\\\\InteractionRepository.cs:line%20115\\\\r\\\\n%20%20%20at%20VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo%20inspectionInfo,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line%20237\\\\r\\\\n%20%20%20at%20VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo%20inspectionInfo)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line%2036&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The%20underlying%20provider%20failed%20on%20Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout%20expired.%20%20The%20timeout%20period%20elapsed%20prior%20to%20obtaining%20a%20connection%20from%20the%20pool.%20%20This%20may%20have%20occurred%20because%20all%20pooled%20connections%20were%20in%20use%20and%20max%20pool%20size%20was%20reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Common.ADP.ExceptionWithStackTrace(Exception%20e)\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}&amp;inspectorId=35185", 3, "Non HTTP response code: java.net.URISyntaxException/Non HTTP response message: Illegal character in query at index 83: https://dev-vip-proxied.th.gov.bc.ca/vip-api/api/v1/inspection/assign?inspectionId={&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;One%20or%20more%20errors%20occurred.&quot;,&quot;exceptionType&quot;:&quot;System.AggregateException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Threading.Tasks.Task.ThrowIfExceptional(Boolean%20includeTaskCanceledExceptions)\\\\r\\\\n%20%20%20at%20System.Threading.Tasks.Task`1.GetResultCore(Boolean%20waitCompletionNotification)\\\\r\\\\n%20%20%20at%20CVSE.Model.CVNSCEntities.GetNextCustomSequenceValue(String%20sequenceName)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVNSC\\\\\\\\CVSE.Model\\\\\\\\CustomEntityMethods.cs:line%209\\\\r\\\\n%20%20%20at%20VIP.Data.Repositories.Inspection.InspectionRepository.AddNew(CvVipInspection%20entity,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Data\\\\\\\\Repositories\\\\\\\\Inspection\\\\\\\\InspectionRepository.cs:line%2041\\\\r\\\\n%20%20%20at%20VIP.Service.Inspection.InspectionService.StartInspection(InspectionStartInfo%20inspectionInfo,%20Dictionary`2%20headers)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.Service\\\\\\\\Inspection\\\\\\\\InspectionService.cs:line%20209\\\\r\\\\n%20%20%20at%20VIP.API.Controllers.InspectionController.InspectionStart(InspectionStartInfo%20inspectionInfo)%20in%20E:\\\\\\\\Tomcat-Apps\\\\\\\\Jenkins\\\\\\\\workspace\\\\\\\\PTMP\\\\\\\\CVIP\\\\\\\\DEV-TST\\\\\\\\CVIP_1.0-DEV_Build_App_Branch\\\\\\\\CVVIP\\\\\\\\VIP.API\\\\\\\\Controllers\\\\\\\\InspectionController.cs:line%2036&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;The%20underlying%20provider%20failed%20on%20Open.&quot;,&quot;exceptionType&quot;:&quot;System.Data.Entity.Core.EntityException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;EnsureConnectionAsync&gt;d__9.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteInTransactionAsync&gt;d__3d`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.Objects.ObjectContext.&lt;ExecuteStoreQueryReliablyAsync&gt;d__6c`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Internal.LazyAsyncEnumerator`1.&lt;FirstMoveNextAsync&gt;d__0.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.&lt;SingleAsync&gt;d__2d`1.MoveNext()&quot;,&quot;innerException&quot;:{&quot;message&quot;:&quot;An%20error%20has%20occurred.&quot;,&quot;exceptionMessage&quot;:&quot;Timeout%20expired.%20%20The%20timeout%20period%20elapsed%20prior%20to%20obtaining%20a%20connection%20from%20the%20pool.%20%20This%20may%20have%20occurred%20because%20all%20pooled%20connections%20were%20in%20use%20and%20max%20pool%20size%20was%20reached.&quot;,&quot;exceptionType&quot;:&quot;System.InvalidOperationException&quot;,&quot;stackTrace&quot;:&quot;%20%20%20at%20System.Data.Common.ADP.ExceptionWithStackTrace(Exception%20e)\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;&gt;c__DisplayClass4.&lt;&lt;ExecuteAsync&gt;b__3&gt;d__6.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.&lt;ExecuteAsyncImplementation&gt;d__9`1.MoveNext()\\\\r\\\\n---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---\\\\r\\\\n%20%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\\\r\\\\n%20%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task%20task)\\\\r\\\\n%20%20%20at%20System.Data.Entity.Core.EntityClient.EntityConnection.&lt;OpenAsync&gt;d__8.MoveNext()&quot;}}}&amp;inspectorId=35185", 2], "isController": false}, {"data": ["SaveInspectionDetails", 300, 289, "500/Internal Server Error", 259, "401/Unauthorized", 30, null, null, null, null, null, null], "isController": false}, {"data": ["SaveInspectionVehicle", 300, 263, "500/Internal Server Error", 233, "401/Unauthorized", 30, null, null, null, null, null, null], "isController": false}, {"data": ["SaveInspectionMeasurements", 300, 271, "500/Internal Server Error", 241, "401/Unauthorized", 30, null, null, null, null, null, null], "isController": false}]}, function(index, item){
        return item;
    }, [[0, 0]], 0);

});
